import type { Metadata } from "next";
import "../../globals.css";
import { SideBar } from "@/components/admin/SideBar";
import { SidebarProvider } from "@/components/ui/sidebar";
import UserButton from "@/components/header/UserButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
    return (
      <html lang="en">
        <body className="min-h-screen flex flex-col">
          <SidebarProvider>
            <SideBar />
            <main className="flex justify-center items-start flex-grow">
              {/* Sayfa içeriğini buraya yerleştirebilirsiniz */}
              <div className="flex justify-start items-start mx-4">
                {children}
              </div>
            </main>
          </SidebarProvider>
        </body>
      </html>
    )
}
